name: Build documentation

on: 
  push:
    branches: [ main ]
    paths: [ 'docs/**', '.github/workflows/build-docs.yml' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pdm install -dG doc

    - name: Build HTML docs
      run: pdm run doc
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
